version: '3.6'

services:
  backend:
    image: wordmemorization
    container_name: word-memorization
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0
    container_name: mongo-database
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
